### ISSUE TITLE
Check for reindexing (ReindexingRequiredError)

### ISSUE THREAD

**Issue by bb4L** [dipdup-net/dipdup-py#164]
Hey there

I wanted to update dipdup to version 3.1.1 from 3.0.4

Now i'm wondering if there is a way to check if reindexing is required / reenable reindexing?

Because for automatic deployment i don't want to have to run the `schema wipe` with every deployment just for the case that i might have to reindex...

**Comment by Anshit01** [comment]
I think it's important to give this choice to the user. The need for automatic reindexing can vary from project to project.
Personally, I would like to enable automatic reindexing.

The easiest solution is to give a cli option like `--auto-reindex`.
A more flexible solution can be to have this as a configuration in `dipdup.yml` where people can even choose on which types of reindexing reasons (`dipdup.enums.ReindexingReason`) they want to auto reindex.

**Comment by veqtor** [comment]
`--auto-reindex` cli option would be great

**Comment by droserasprout** [comment]
Thanks for the feedback, everybody!

We've ended up with a separate section in config. Something like this:

```yaml
spec_version: ...
advanced:
  postpone_jobs: true
  early_realtime: true
  skip_hasura: true
  reindex:
    # NOTE: Default action
    _: raise
    CONFIG_HASH_MISMATCH: auto
    SCHEMA_HASH_MISMATCH: raise
    MANUAL: ignore
```

Flags will be still in CLI having priority over config. It's not a final agreed solution tho.
