### ISSUE TITLE
Unable to select operation which has entrypoint using source filter in dipdup.yml

### ISSUE THREAD

**Issue by pravin-d** [dipdup-net/dipdup-py#183]
Given a transaction which is a contract call (has entrypoint key)
The below does not capture the transaction
```
handlers:
      - callback: on_callback
        pattern:
          - type: transaction
            source: contract_address
```
