### ISSUE TITLE
Can't parse big maps where values are sets

### ISSUE THREAD

**Issue by konchunas** [dipdup-net/dipdup-py#204]
When I try to parse contract which has `big_map(address, set(nat))` field in storage I get the following error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for YupanaStorage
storage -> markets -> key
  value is not a valid list (type=type_error.list)
```

This didn't happen in version 3.
  
 Config example to reproduce this can be found below.
 <details> <summary>dipdup.yml</summary>
 
```yml
spec_version: 1.2
package: yupana_indexer

contracts:
  ytoken:
    address: KT1LTqpmGJ11EebMVWAzJ7DWd9msgExvHM94
    typename: yupana

datasources:
  tzkt_testnet:
    kind: tzkt
    url: https://api.hangzhou2net.tzkt.io/

indexes:
  ytoken:
    kind: operation
    datasource: tzkt_testnet
    contracts:
      - ytoken
    handlers:
      - callback: on_enter_market
        pattern:
          - destination: ytoken
            entrypoint: enterMarket
```
</details>
