### ISSUE TITLE
dipdup init does not work as expected with this contract: KT1WgoWgvKJiQ43MkeLoG7LtSZMxeED7Rn8T

### ISSUE THREAD

**Issue by smak0v** [dipdup-net/dipdup-py#255]
```
spec_version: 1.2
package: crypto_horses

database:
  kind: sqlite
  path: crypto_horses.sqlite3

contracts:
  crypto_horses_testnet:
    address: KT1WgoWgvKJiQ43MkeLoG7LtSZMxeED7Rn8T
    typename: crypto_horses

datasources:
  tzkt_testnet:
    kind: tzkt
    url: https://hangzhou2net.tzkt.io

indexes:
  crypto_horses:
    kind: operation
    contracts:
      - crypto_horses_testnet
    datasource: tzkt_testnet
    handlers:
      - callback: on_race_launch
        pattern:
          - destination: crypto_horses_testnet
            entrypoint: launch_race
```
