### ISSUE TITLE
5.0.0rc2 - Weird random non-matching with skip_once

### ISSUE THREAD

**Issue by veqtor** [dipdup-net/dipdup-py#265]
**Steps to reproduce:**
Use a bigmap index with skip_once, using two contracts

**What did you expect to happen:**
Matches all handlers / contracts

**What actually happened:**
Randomly matches either

### Environment

* **Python version:** 3.10
* **DipDup version or commit hash:** 5.0.0rc2
* **Database engine version:**
* **Hasura version:**
* **Are you in docker?**
* **Can you reproduce this issue on `master`?**

### Attachment checklist

- [ ] General: DipDup logs (~100 lines above stacktrace)
- [x] General: `config export` output
- [ ] General: `models.py`
- [ ] SQL issues: `schema export` output
- [ ] Hasura issues: Hasura container logs

config needed to replicate:
```
contracts:
  HEN_swap_v1:
    address: KT1RoynRPMidohYtsGc3HxgEWbqhDAtNGVHb
    typename: hen_minter

  HEN_objkts:
    address: KT1Q4TLSG8TZBgp9rbLxUdZ1gaVNmm2t52C5
    typename: hen_objkts

templates:
  hicetnunc_fast_bm:
    kind: big_map
    datasource: <datasource>
    handlers:
      - callback: hicetnunc.objkt.bm.on_royalties
        contract: <swap_v1>
        path: royalties
      - callback: hicetnunc.objkt.bm.on_metadata
        contract: <objkt>
        path: token_metadata
      - callback: hicetnunc.objkt.bm.on_ledger_update
        contract: <objkt>
        path: ledger

datasources:
  tzkt_testnet:
    kind: tzkt
    url: https://api.hangzhou2net.tzkt.io/
    http:
      retry_count: 100
      retry_sleep: 0.1
      retry_multiplier: 1.2
      ratelimit_rate: 200
      ratelimit_period: 1
      connection_limit: 10000

indexes:
  hicetnunc_fast_bm:
    template: hicetnunc_fast_bm
    values:
      datasource: tzkt_testnet
      objkt: HEN_objkts
      swap_v1: HEN_swap_v1
```
