### ISSUE TITLE
`logging` config section

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#288]
**What feature would you like to see in DipDup?**

In config:

```yaml
logging:
  '': INFO
  dipdup: WARNING
```

**Why do you need this feature, what's the use case?**

Python logging config is too complex.

**Is there a workaround currently?**

`-l logging.yml` option in CLI
