### ISSUE TITLE
Docker image without codegen

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#448]
`datamodel-code-generator` dependencies:

```toml
[package.dependencies]
argcomplete = ">=1.10,<3.0"
black = ">=19.10b0"
genson = ">=1.2.1,<2.0"
inflect = ">=4.1.0,<6.0"
isort = ">=4.3.21,<6.0"
jinja2 = ">=2.10.1,<4.0"
openapi-spec-validator = ">=0.2.8,<0.4"
prance = ">=0.18.2,<1.0"
pydantic = {version = ">=1.9.0,<2.0", extras = ["email"], markers = "python_version >= \"3.10\""}
PySnooper = ">=0.4.1,<2.0.0"
toml = ">=0.10.0,<1.0.0"
typed-ast = {version = ">=1.5.0", markers = "python_full_version >= \"3.9.8\""}
```
