### ISSUE TITLE
Duplicate entrypoints in operation pattern are not aliased

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup-py#470]
**Steps to reproduce:**

```yaml
- callback: on_mint
              pattern:
                  - destination: minter_testnet
                    entrypoint: mint
                    type: transaction
                  - destination: nft_testnet
                    source: minter_testnet
                    entrypoint: mint
                    type: transaction
```

```python
async def on_mint(
    ctx: HandlerContext,
    mint: Transaction[MintParameter, NftStorage],
) -> None:
```

```text
async def on_mint(
    ctx: HandlerContext,
    mint: Transaction[MintParameter, NftStorage],
) -> None:
```

**What did you expect to happen:**

An argument for each item in the pattern.

**What actually happened:**

One argument in the signature for both items.

### Environment

* **Python version:** n/a
* **DipDup version or  commit hash:** n/a
* **Database engine version:** n/a
* **Hasura version:** n/a
* **Are you in docker?** n/a
* **Can you reproduce this issue on `master`?** +
